_commit: 0.3.1
_src_path: gh:georglauterbach/template.git
code_binary_enabled: true
code_library_enabled: false
dev_container_enabled: true
dev_container_use_hermes: true
git_ecosystem: github
git_ecosystem_username: georglauterbach
lang_container_enabled: false
lang_python_enabled: false
lang_rust_enabled: true
lang_shell_enabled: false
project_changelog_enabled: true
project_description: '`stinkpot-rs` is a sqlite-backed shell-history searcher. It
    is a much tinier [Atuin](https://atuin.sh). Its goal is to be minimal: no AI,
    no sync, just SQLite-backed history search.'
project_license: ''
project_name: stinkpot
